### ISSUE TITLE
Create proper DB schema

### ISSUE THREAD

**Issue by GeoDoo** [GeoDoo/post-your-standup#4]
**I guess the db to use is also to be decided!!**

We need to save several data like the following:

- users
- Jira projects
- Jira board columns (or statuses)
- channels
- other data for validation and authorization etc

**Comment by elefher** [comment]
> **I guess the DB to use is also to be decided!!**

I was thinking that we can use MongoDB. The main reason that I choose NoSQL database over the traditional SQL(MySQL, PostgreSQL, etc) is the flexibility that you obtain when using it. I know that our data here is relational (which means we should use an SQL database) but I think in our case will be much easier in the future to append a new property in a JSON instead of creating new columns in a table or new table. Of course, we can discuss that if you want.

> We need to save several data like the following:
> 
> * users
> * Jira projects
> * Jira board columns (or statuses)
> * channels
> * other data for validation and authorization etc

All these data and much more will fit easily in MongoDB. No worries!

Regardless of the DB, either Mongo or MySql I suggest using the following technologies.
- Docker for the DB. we will use this docker locally and on the prod server. Also, this docker is going to be the start to move the whole environment into dockers.
- I have already started and set up a docker-compose.yml file, have a look in my branch.
- I will create files that will read the env variables for username passwords, etc. 
- After finishing the docker environment set up I will install and use either Mongoose if we go with MongoDB or Sequelize if we go with Mysql solution.
- Create the first table to store user data and more.
   - Workspace storage: name, token, email, Jira domain
   - User storage: name, email, ?preferences
Let's discuss what else needs to be done in this task.

You can have a look at these resources if you want.
https://phoenixnap.com/kb/docker-mongodb
https://docs.docker.com/compose/
https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

**Comment by GeoDoo** [comment]
Cool, yes we should dockerize the whole app not only the database, I agree!

I had problems with deploying because there were some merge conflicts on git pull 🤦 

I like it, you are the DB master, so you pick what is the best Mongo or MySQL 

Exciting!!!
